version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
  migrate:
    extends:
      service: backend
    command: python manage.py migrate
  web_run:
    extends:
      service: backend
    command: gunicorn -c gunicorn.py.ini backend.wsgi
    ports:
      - "5000:5000"
    networks:
      - app-test

  frontend:
    container_name: front
    build:
      context: ./backend/frontend
    restart: always
    tty: true
    volumes:
      - './backend/frontend:/frontend'
    ports:
      - '3000:3000'
    networks:
      - app-test
    environment:
      - NODE_ENV=development
    command: 'npm start'


networks:
  app-test:
    driver: bridge



